import { h } from "preact"
import { useState } from "preact/hooks"
import { Upload } from "preact-feather"
import { Field, FieldGroup, ButtonImg } from "../Controls"
import { T } from "../Translations"
import { useDatasContext, useUiContext } from "../../contexts"
import { showConfirmationModal } from "../Modal"
import boardPresets from "../../configuration/boardPresets"
import { applyBoardPreset, getBoardPresetById } from "../../configuration/applyBoardPreset"
import {
    parseSnapshotFromText,
    snapshotImportErrorMessage,
} from "../../configuration/configurationSnapshot"

const IMPORTED_PRESET_ID = "imported-configuration-h"
const IMPORT_FILE_INPUT_ID = "board-preset-import-h"

const presetListWithImported = (importedPreset) =>
    importedPreset ? [importedPreset, ...boardPresets] : boardPresets

const labelFromImportFile = (filename) => {
    const base = filename.replace(/^.*[/\\]/, "").trim()
    return base || T("Imported configuration")
}

const buildImportSuccessMessage = (applied, label, unknownCount = 0) => {
    const detail =
        unknownCount > 0
            ? ` (${unknownCount} ${T("unknown ids ignored")})`
            : ""
    return `${T("Imported")} ${applied} ${T("settings from")} ${label}${detail}.`
}

const showImportToast = (toasts, variant, content, literal = false) => {
    if (!content) return
    toasts.addToast({
        type: variant === "success" ? "success" : "error",
        content,
        literal,
    })
}

const presetConfirmContent = (preset) => (
    <div>
        <p>
            {T(
                "This will overwrite settings that are defined in the preset. Other tabs are included."
            )}
        </p>
        <p>
            <strong>{preset.label}</strong>
        </p>
        {preset.description && <p>{preset.description}</p>}
    </div>
)

const BoardPresetPicker = ({ onApplied }) => {
    const { configuration, importConfigurationSnapshot } = useDatasContext()
    const { modals, toasts } = useUiContext()
    const [activeId, setActiveId] = useState("")
    const [importedPreset, setImportedPreset] = useState(null)
    const [importFeedback, setImportFeedback] = useState(null)

    const allPresets = presetListWithImported(importedPreset)
    const activePreset = getBoardPresetById(allPresets, activeId)

    const applyPreset = (preset, newActiveId) => {
        const result =
            preset.id === IMPORTED_PRESET_ID
                ? importConfigurationSnapshot({ values: preset.values })
                : applyBoardPreset(configuration.current, preset)
        setActiveId(newActiveId)
        onApplied?.({ presetId: preset.id })
        return result
    }

    const finishImportedPresetApply = (preset) => {
        setImportedPreset(preset)
        const { applied, unknown } = applyPreset(preset, IMPORTED_PRESET_ID)
        const successMsg = buildImportSuccessMessage(
            applied,
            preset.label,
            unknown.length
        )
        setImportFeedback({
            variant: "success",
            message: successMsg,
        })
        showImportToast(toasts, "success", successMsg, true)
    }

    const confirmApplyPreset = (preset, newActiveId) => {
        showConfirmationModal({
            modals,
            title: T("Apply board preset"),
            content: presetConfirmContent(preset),
            button1: { text: T("Cancel") },
            button2: {
                text: T("Apply"),
                cb: () => {
                    if (preset.id === IMPORTED_PRESET_ID) {
                        finishImportedPresetApply(preset)
                    } else {
                        applyPreset(preset, newActiveId)
                    }
                },
            },
        })
    }

    const confirmBeforeImport = () => {
        const importPreset = {
            id: IMPORTED_PRESET_ID,
            label: T("Import configuration.h"),
            description: T(
                "You will choose a configuration.h file generated by this tool (snapshot at end of file)."
            ),
        }
        showConfirmationModal({
            modals,
            title: T("Apply board preset"),
            content: presetConfirmContent(importPreset),
            button1: { text: T("Cancel") },
            button2: {
                text: T("Apply"),
                cb: () => {
                    document.getElementById(IMPORT_FILE_INPUT_ID)?.click()
                },
            },
        })
    }

    const reportImportError = (message) => {
        const text = T(message)
        setImportFeedback({ variant: "error", message: text })
        showImportToast(toasts, "error", text, true)
    }

    const handleSelectChange = (newId) => {
        if (newId === activeId) return

        if (!newId) {
            setActiveId("")
            return
        }

        const preset = getBoardPresetById(allPresets, newId)
        if (!preset) return

        confirmApplyPreset(preset, newId)
    }

    const handleImportFile = (file) => {
        if (!file) return
        setImportFeedback(null)

        const reader = new FileReader()
        reader.onerror = () => {
            reportImportError("Could not read the selected file.")
        }
        reader.onload = () => {
            const parsed = parseSnapshotFromText(String(reader.result || ""))
            if (!parsed.ok) {
                reportImportError(snapshotImportErrorMessage(parsed))
                return
            }

            const preset = {
                id: IMPORTED_PRESET_ID,
                label: labelFromImportFile(file.name),
                description: T(
                    "Imported from configuration.h (embedded snapshot)"
                ),
                values: parsed.snapshot.values,
            }

            finishImportedPresetApply(preset)
        }
        reader.readAsText(file)
    }

    if (!boardPresets.length) return null

    const presetOptions = [
        { label: T("None (current settings)"), value: "" },
        ...(importedPreset
            ? [{ label: importedPreset.label, value: importedPreset.id }]
            : []),
        ...boardPresets.map((preset) => ({
            label: preset.label,
            value: preset.id,
        })),
    ]

    const feedbackColor =
        importFeedback?.variant === "success"
            ? "#32b643"
            : importFeedback?.variant === "error"
              ? "#ff0000"
              : undefined

    return (
        <FieldGroup
            id="boardPreset"
            label={T("Board preset")}
            className="board-preset-picker"
        >
            <p class="m-1 board-preset-intro">
                {T(
                    "Choose a board profile or import configuration.h (confirmation required). Fine-tune in each tab afterward."
                )}
            </p>
            <div class="board-preset-row">
                <Field
                    inline
                    className="fit-content"
                    type="select"
                    label={T("Preset")}
                    id="boardPresetSelect"
                    options={presetOptions}
                    value={activeId}
                    setValue={(val, update = false) => {
                        if (update) return
                        handleSelectChange(val)
                    }}
                />
                <input
                    type="file"
                    accept=".h,.txt,text/plain"
                    class="d-none"
                    id={IMPORT_FILE_INPUT_ID}
                    onChange={(e) => {
                        const file = e.target.files && e.target.files[0]
                        handleImportFile(file)
                        e.target.value = ""
                    }}
                />
                <ButtonImg
                    m1
                    icon={<Upload />}
                    label={T("Import configuration.h")}
                    onclick={confirmBeforeImport}
                />
            </div>
            {importFeedback && (
                <p
                    class={`m-1 board-preset-import-feedback board-preset-import-feedback--${importFeedback.variant}`}
                    style={feedbackColor ? { color: feedbackColor } : undefined}
                    role="status"
                >
                    {importFeedback.message}
                </p>
            )}
            {activePreset?.description && (
                <p class="m-1 board-preset-intro">{activePreset.description}</p>
            )}
        </FieldGroup>
    )
}

export { BoardPresetPicker, IMPORTED_PRESET_ID }
